# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  vmImage: ubuntu-latest

steps:
- script: | 
    echo Installing Jfrog CLI latest version 
    curl -fL https://install-cli.jfrog.io | sh
    jf --help
    echo "job id : $SYSTEM_JOBID"
    echo "plan id : $SYSTEM_PLANID"
    echo "hub : $SYSTEM_HUB"
    echo "project id : $SYSTEM_TEAMPROJECTID"
  displayName: JFrog CLI Installation
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    SYSTEM_JOBID: $(System.JobId)
    SYSTEM_PLANID: $(System.PlanId)
    SYSTEM_TEAMPROJECTID: $(System.TeamProjectId)
    SYSTEM_HUB: $(System.HostType)
    SYSTEM_COLLECTIONURI: $(System.CollectionUri)