# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  vmImage: ubuntu-latest

steps:
- script: | 
    echo Installing Jfrog CLI latest version 
    curl -fL https://install-cli.jfrog.io | sh
    jf --help
  displayName: JFrog CLI Installation